### ISSUE TITLE
channel

### ISSUE THREAD

**Issue by ghost** [Hiteke/Discord-gift-generator#3]
💀

**Comment by AkhilJose2019** [comment]
use client.channels.cache.get('id')

**Comment by AkZuza** [comment]
ur making a mistake
u cant get a channel from a client
u can a channel from a guild and u can get a guid from a channel so this code might work
Code is using discord.js 12.0.2

`const guild = client.guilds.cache.get([guild id]);
const channel = guild.channels.cache.get([channel id]);
`
